import FAQ from "../pages/FAQ/FAQ";
import Home from "../pages/Home";
import Matches from "./Matches/Matches";
import RegisterForm from "./Register/RegisterForm";
import LandingPage from "./LandingPage/LandingPage";
import LoginPage from "./LoginPage";
import Sessions from "./Sessions/Sessions";
import Profile from "./Profile/Profile";
import Chat from "./Chat/Chat";
import Questions from "./Questions/Questions";
import Meetings from "./Meetings/Meetings";
export { FAQ, Home, Matches, RegisterForm, LandingPage, LoginPage, Sessions,Profile,Chat,Questions,Meetings };
