// All User Types
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = " USER_LOGIN_ERROR";

export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = " USER_REGISTER_ERROR";

export const GET_USER_INFO = "USER_INFO_START";
export const GET_USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "USER_INFO_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

//All Matches Types
export const GET_USER_MATCHES = "GET_USER_MATCHES";
export const GET_USER_MATCHES_SUCCESS = "GET_USER_MATCHES_SUCCESS";
export const GET_USER_MATCHES_ERROR = "GET_USER_MATCHES_ERROR";

export const CREATE_MATCHES = "CREATE_MATCHES";
export const CREATE_MATCHES_SUCCESS = "CREATE_MATCHES_SUCCESS";
export const CREATE_MATCHES_ERROR = "CREATE_MATCHES_ERROR";

export const UPDATE_MATCHES = "UPDATE_MATCHES";
export const UPDATE_MATCHES_SUCCESS = "UPDATE_MATCHES_SUCCESS";
export const UPDATE_MATCHES_ERROR = "UPDATE_MATCHES_ERROR";

//All Sessions Types
export const GET_SESSIONS = "GET_SESSIONS";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR";

//Admin Dashboard Types
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_STATISTICS_SUCCESS = "GET_STATISTICS_SUCCESS";
export const GET_STATISTICS_ERROR = "GET_STATISTICS_ERROR";

export const GET_MENTORS_LIST = "GET_MENTORS_LIST";
export const GET_MENTORS_LIST_SUCCESS = "GET_MENTORS_LIST_SUCCESS";
export const GET_MENTORS_LIST_ERROR = "GET_MENTORS_LIST_ERROR";

export const GET_MENTEES_LIST = "GET_MENTEES_LIST";
export const GET_MENTEES_LIST_SUCCESS = "GET_MENTEES_LIST_SUCCESS";
export const GET_MENTEES_LIST_ERROR = "GET_MENTEES_LIST_ERROR";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const GET_ADMIN_SESSIONS = "GET_ADMIN_SESSIONS";
export const GET_ADMIN_SESSIONS_SUCCESS = "GET_ADMIN_SESSIONS_SUCCESS";
export const GET_ADMIN_SESSIONS_ERROR = "GET_ADMIN_SESSIONS_ERROR";

export const UPDATE_MENTOR_REGISTERATION = "UPDATE_MENTOR_REGISTERATION";
export const UPDATE_MENTOR_REGISTERATION_SUCCESS =
  "UPDATE_MENTOR_REGISTERATION_SUCCESS";
export const UPDATE_MENTOR_REGISTERATION_ERROR =
  "UPDATE_MENTOR_REGISTERATION_ERROR";

export const GET_MENTOR_APPLICATIONS = "GET_MENTOR_APPLICATIONS";
export const GET_MENTOR_APPLICATIONS_SUCCESS =
  "GET_MENTOR_APPLICATIONS_SUCCESS";
export const GET_MENTOR_APPLICATIONS_ERROR = "GET_MENTOR_APPLICATIONS_ERROR";
